<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_United States</name>
   <tag></tag>
   <elementGuidId>840a6603-9e42-4e24-9d06-64a7efc2c057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icp-touch-link-country > span.icp-color-base</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-touch-link-country']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7757efe9-74c3-4c60-999c-f8173f8032f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icp-color-base</value>
      <webElementGuid>fb36e78a-3ccb-426d-aa1f-6e159e99393b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>United States</value>
      <webElementGuid>04cccc79-4c8d-479f-a35d-e0dd23fc626e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-touch-link-country&quot;)/span[@class=&quot;icp-color-base&quot;]</value>
      <webElementGuid>df262ac6-8fdc-4c1d-9eab-d3ad6ea1e95e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='icp-touch-link-country']/span[2]</value>
      <webElementGuid>9aead4f3-7629-41b1-a357-c405046ccdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a[3]/span[2]</value>
      <webElementGuid>0309c040-38b5-45aa-b8a1-6b7fca328069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'United States' or . = 'United States')]</value>
      <webElementGuid>bb09a7e0-955d-4770-8719-f79fa514657a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
