<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_India</name>
   <tag></tag>
   <elementGuidId>e098c17d-4c4d-4bc8-83b2-154cb440b627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icp-dropdown_8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-dropdown_8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f314a8c-576d-4c66-aa86-a16fba14563c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>665f41b3-b4ac-4851-9176-c87ceba43e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>3fadbfb8-ef72-4b05-bc3f-ab92a850e7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>889dfd38-4111-48a9-a701-62da87a91ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;https://www.amazon.in/?ref_=icp_country_from_us&quot;}</value>
      <webElementGuid>9d389559-ddc8-4d85-8f41-53ce1e473081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icp-dropdown_8</value>
      <webElementGuid>6d5efb4c-3680-41b0-9484-17d0eee90079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>2e3535a4-0fd7-4fa7-828a-13d26af18ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> India</value>
      <webElementGuid>48910f01-ecfc-44cd-b707-3abaa93ff756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-dropdown_8&quot;)</value>
      <webElementGuid>6bf4b67a-79da-45e6-b726-7e6060f137ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='icp-dropdown_8']</value>
      <webElementGuid>680efd83-f650-4f52-9bff-f6c625735d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='icp-dropdown-item-8']/a</value>
      <webElementGuid>d715780b-ce5f-4151-a326-b3f425148087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'India')]</value>
      <webElementGuid>bbf05f8b-c503-40e0-b229-4729a6ef8d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[14]</value>
      <webElementGuid>f48530e9-0e68-4e8e-9559-5757451324e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/ul/li[9]/a</value>
      <webElementGuid>5aa1a7f5-589d-4db0-874b-6620b4d02e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'icp-dropdown_8' and (text() = ' India' or . = ' India')]</value>
      <webElementGuid>77187811-f11b-43e4-921c-7cb2596dcd1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
