<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_United Kingdom</name>
   <tag></tag>
   <elementGuidId>30bffbf9-b82e-4066-b33d-69d97b5f5fd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icp-dropdown_20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-dropdown_20']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d9464b38-d654-4f03-94ed-eee54f00364e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ed197fbf-cb0b-4af0-a8af-372f7c2e5ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>fcd2806f-e6df-40f9-8736-507cecdb6023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22cbb2db-b362-43fe-b412-8f0f1c384878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;https://www.amazon.co.uk/?ref_=icp_country_from_us&quot;}</value>
      <webElementGuid>63462bb6-870d-4378-a89f-a08262640f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icp-dropdown_20</value>
      <webElementGuid>7c9e8e11-bedd-4470-a5a3-cbb6c1b6b3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>8db75148-a5f5-4653-a078-145bf63bba8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> United Kingdom</value>
      <webElementGuid>9f7b1409-6889-4c6c-9f8e-04c77498d03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-dropdown_20&quot;)</value>
      <webElementGuid>7b1e2faa-e8a3-459f-abc6-7c40f067a827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='icp-dropdown_20']</value>
      <webElementGuid>f191ebbf-1aac-4cbe-b2b4-da41e26fba0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='icp-dropdown-item-20']/a</value>
      <webElementGuid>04fbc819-4fcd-4444-a4f1-9aea4b1d5ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'United Kingdom')]</value>
      <webElementGuid>0c650268-cb2a-46f3-a432-430983b1c3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[26]</value>
      <webElementGuid>58843bc5-5102-45ad-b736-adb12784994d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/ul/li[21]/a</value>
      <webElementGuid>e3638545-80bf-49bf-8623-5bcd3ae75ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'icp-dropdown_20' and (text() = ' United Kingdom' or . = ' United Kingdom')]</value>
      <webElementGuid>14fd8f9e-cee1-4b42-9123-95352963ffc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
