<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_Login_Data Driven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>721bd8f6-3555-4dfc-b914-b062ba92bccf</testSuiteGuid>
   <testCaseLink>
      <guid>f606b1cd-53e3-4220-bb4f-1aa396350fd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven_Testing/TC_Amazon_Login_Excel_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>112edc63-a32d-4de6-91f6-e50839d144ae</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_Login_dataDriven/Amazon_Login_Details</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>112edc63-a32d-4de6-91f6-e50839d144ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>4dc267b7-7231-4902-bb30-5e7132d5f24a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>112edc63-a32d-4de6-91f6-e50839d144ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>baadf428-e9f5-4d34-96bc-caf287cea3a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>112edc63-a32d-4de6-91f6-e50839d144ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>76d59696-d755-48b3-9c73-ac01fba22f00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>112edc63-a32d-4de6-91f6-e50839d144ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>repassword</value>
         <variableId>8dfab08f-508e-4dac-8874-db236844c160</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
